<!-- Favicons — generated by realfavicongenerator.net, stored in assets/img/favicon_io/ -->
<link rel="icon" type="image/x-icon" href="/assets/img/favicon_io/favicon.ico">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon_io/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicon_io/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicon_io/apple-touch-icon.png">
<link rel="manifest" href="/assets/img/favicon_io/site.webmanifest">
