<?php
// consolehtml.php — Real Mode coding challenge (JS targeting real HTML elements).
// The learner edits both HTML and JS — changes appear live in the preview iframe.
// Exercise content (task card, HTML template, check rules) is generated by the
// Claude API when the learner clicks "New Challenge" — see the inline <script>.
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/functions.php';
require_login();

$slug  = isset($_GET['topic']) ? $_GET['topic'] : '';
$topic = $slug !== '' ? ucwords(str_replace('-', ' ', $slug)) : 'Unknown Topic';

// Difficulty level — this page handles BOTH "intermediate" and "advanced".
// We read it from the URL (set by mode.php) and whitelist the value so an
// unexpected input falls back to "intermediate" (the safer of the two, since
// advanced assumes the learner already knows event listeners).
$level = isset($_GET['level']) ? $_GET['level'] : 'intermediate';
if ($level !== 'intermediate' && $level !== 'advanced') {
    $level = 'intermediate';
}

// Badge shown next to the task title. We compute both the visible label
// (emoji + text) and the CSS modifier class from $level so every badge
// on the page stays in sync with the chosen difficulty.
// Using a ternary because there are only two possible values here —
// the third level (beginner) lives on consolenohtml.php.
$level_label = $level === 'advanced' ? '🌳 Advanced' : '🌿 Intermediate';
$level_class = $level === 'advanced' ? 'c-mode-advanced' : 'c-mode-intermediate';

// Default starter HTML — replaced by the AI-generated template once the API responds.
$starter_html = implode("\n", [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8">',
    '</head>',
    '<body>',
    '  <h2>' . $topic . '</h2>',
    '  <button id="btn">Click me</button>',
    '  <p id="output">Result will appear here.</p>',
    '</body>',
    '</html>',
]);
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php include __DIR__ . '/includes/favicons.php'; ?>
  <title>Real Mode — <?= h($topic) ?> — SocraticJS</title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/codemirror.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/theme/dracula.min.css">

  <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body class="page--console">

  <!-- ── Navigation ─────────────────────────────────────────────── -->
  <nav class="nav">
    <a href="/index.php"><img class="nav__logo" src="/assets/img/logo.png" alt="SocraticJS logo"></a>
    <a class="nav__link" href="/about.php">about</a>
    <div class="nav__right">
      <?php if (is_logged_in()): ?>
        <span class="nav__greeting">Hi, <?= h($_SESSION["username"]) ?></span>
        <a class="nav__link nav__link--logout" href="/logout.php">logout</a>
      <?php else: ?>
        <a class="nav__link" href="/login.php">login</a>
        <a class="nav__link" href="/register.php">signUp</a>
      <?php endif; ?>
    </div>
  </nav>

  <!-- ── Real Mode widget — HTML editor + JS editor + live preview ── -->
  <div class="console__layout">

    <div class="c-challenge-actions">
      <button class="c-btn c-btn--challenge" id="new-challenge-btn" type="button">New Challenge</button>
    </div>

    <!-- Task card — populated after clicking New Challenge -->
    <div class="c-task-card">
      <div class="c-task-title" id="task-title">
        Ready for a new challenge?
        <span class="c-mode-badge <?= h($level_class) ?>"><?= h($level_label) ?></span>
      </div>
      <div class="c-task-body" id="task-body">
        <p class="c-hint">Click <strong>New Challenge</strong> to generate a real-mode exercise for <?= h($topic) ?>.</p>
      </div>
    </div>

    <!-- Main toolbar -->
    <div class="c-toolbar">
      <span class="c-toolbar__hint">Edit HTML freely, then write JS to target it</span>
      <div class="c-spacer"></div>
      <button class="c-btn c-btn--reset" id="reset-btn">Reset</button>
      <button class="c-btn c-btn--run"   id="run-btn">Run ▶</button>
    </div>

    <!-- HTML panel — editable in Real mode so learners can experiment with structure -->
    <div class="c-panel">
      <div class="c-panel-header">
        <span class="c-dot c-dot--html"></span>
        index.html — edit me!
      </div>
      <textarea id="html-editor"></textarea>
      <!-- Apply HTML button — reloads the iframe with the current HTML editor content -->
      <div class="c-js-toolbar">
        <span class="c-toolbar__hint">Edit the HTML freely, then apply it</span>
        <div class="c-spacer"></div>
        <button class="c-btn c-btn--reset" id="apply-html-btn">Apply HTML ↺</button>
      </div>
    </div>

    <!-- JS panel -->
    <div class="c-panel" id="js-panel">
      <div class="c-panel-header">
        <span class="c-dot c-dot--js"></span>
        script.js — write here
      </div>
      <textarea id="js-editor"></textarea>
      <div class="c-js-toolbar">
        <span class="c-toolbar__hint">Done writing?</span>
        <div class="c-spacer"></div>
        <button class="c-btn c-btn--secondary" id="show-answer-btn">Show answer</button>
        <button class="c-btn c-btn--review" id="review-btn">Review my code ↗</button>
      </div>
    </div>

    <!-- Preview iframe — taller in Real mode so DOM changes are clearly visible -->
    <div class="c-panel">
      <div class="c-panel-header">
        <span class="c-dot c-dot--preview"></span>
        Preview — live
      </div>
      <div class="c-preview-wrap c-preview-wrap--real">
        <iframe id="preview" title="Live preview"></iframe>
      </div>
    </div>

    <!-- Output panel -->
    <div class="c-panel">
      <div class="c-panel-header">
        <span class="c-dot c-dot--out"></span>
        Output &amp; checks
      </div>
      <div class="c-output" id="output">
        <span class="c-hint">Run your code to see results.</span>
      </div>
    </div>

  </div><!-- /.console__layout -->

  <script src="/assets/js/main.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/codemirror.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/mode/xml/xml.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/mode/javascript/javascript.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/mode/htmlmixed/htmlmixed.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/addon/edit/closebrackets.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/addon/edit/matchbrackets.min.js"></script>

  <script>
    function isVoidHtmlTag(tagName) {
      return /^(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)$/i.test(tagName);
    }

    function formatHtmlForEditor(html) {
      if (!html) return '';

      var normalized = String(html).replace(/\r\n?/g, '\n').trim();
      if (!normalized) return '';

      var tokens = normalized
        .replace(/>\s*</g, '>\n<')
        .split('\n');

      var formatted = [];
      var indentLevel = 0;

      tokens.forEach(function (token) {
        var line = token.trim();
        var tagMatch;
        var indentForLine;

        if (!line) return;

        if (/^<\//.test(line)) {
          indentLevel = Math.max(indentLevel - 1, 0);
        }

        indentForLine = new Array(indentLevel + 1).join('  ');
        formatted.push(indentForLine + line);

        if (
          /^<!/.test(line) ||
          /^<\//.test(line) ||
          /\/>$/.test(line) ||
          /^<!--/.test(line) ||
          /^<[^>]+>.*<\/[^>]+>$/.test(line)
        ) {
          return;
        }

        tagMatch = line.match(/^<([a-z0-9-]+)/i);
        if (tagMatch && !isVoidHtmlTag(tagMatch[1])) {
          indentLevel += 1;
        }
      });

      return formatted.join('\n');
    }

    // HTML editor — editable in Real mode so learners can change the structure
    var htmlEditor = CodeMirror.fromTextArea(
      document.getElementById('html-editor'),
      {
        mode:              'htmlmixed',
        theme:             'dracula',
        lineNumbers:       true,
        readOnly:          false,         // editable — this is Real mode
        autoCloseBrackets: true,
        extraKeys: { Tab: function (cm) { cm.replaceSelection('  '); } }
      }
    );
    var currentStarterHtml = formatHtmlForEditor(<?= json_encode($starter_html) ?>);
    htmlEditor.setValue(currentStarterHtml);

    var jsEditor = CodeMirror.fromTextArea(
      document.getElementById('js-editor'),
      {
        mode:              'javascript',
        theme:             'dracula',
        lineNumbers:       true,
        autoCloseBrackets: true,
        matchBrackets:     true,
        indentUnit:        2,
        tabSize:           2,
        indentWithTabs:    false,
        extraKeys: {
          'Ctrl-Enter': run,
          'Cmd-Enter':  run,
          Tab: function (cm) { cm.replaceSelection('  '); }
        }
      }
    );

    var output  = document.getElementById('output');
    var preview = document.getElementById('preview');
    var newChallengeBtn = document.getElementById('new-challenge-btn');
    var isLoadingExercise = false;

    // Base style injected into every preview render — keeps the iframe looking
    // consistent with the dark UI without adding noise to the HTML editor.
    // The learner can still override any of these with their own <style> block.
    // Same background/font as the CodeMirror Dracula editor panels:
    // #282a36 = Dracula bg, #f8f8f2 = Dracula foreground, 14px mono to match editors.
    var BASE_PREVIEW_STYLE =
      '<style>' +
        'body { background: #282a36; color: #f8f8f2; font-family: "JetBrains Mono", "Fira Code", monospace; font-size: 14px; line-height: 1.7; padding: 16px; margin: 0; }' +
      '</style>';

    // The iframe is always built from the current HTML editor content —
    // not a static template — because the learner may have edited the HTML.
    // We prepend the base style so the preview matches the dark UI by default.
    function getIframeTemplate() {
      return BASE_PREVIEW_STYLE + htmlEditor.getValue();
    }

    function run() {
      var userJS = jsEditor.getValue().trim();
      if (!userJS) {
        output.innerHTML = '<span class="c-hint">Write some JavaScript first, then hit Run.</span>';
        return;
      }

      output.innerHTML = '<span class="c-hint">Running…</span>';

      // Load the current HTML into the iframe, then inject the learner's JS
      preview.srcdoc = getIframeTemplate();

      preview.onload = function () {
        var win = preview.contentWindow;
        var doc = preview.contentDocument;

        var logs = [];
        var originalLog = win.console.log.bind(win.console);
        win.console.log = function () {
          var args = Array.prototype.slice.call(arguments);
          logs.push(args.map(function (v) { return String(v); }).join(' '));
          originalLog.apply(null, args);
        };

        var runError = null;
        try {
          var fn = new win.Function(userJS);
          fn();
        } catch (e) {
          runError = e.message;
        }

        var lines = [];

        if (logs.length > 0) {
          logs.forEach(function (line) {
            lines.push('<div class="c-log c-log--plain">&#9656; ' + esc(line) + '</div>');
          });
        }

        if (runError) {
          lines.push('<div class="c-log c-log--err">&#10005; Error: ' + esc(runError) + '</div>');
        }

        lines.push('<hr class="c-divider">');

        var checks = runChecks(doc, userJS, logs);
        checks.forEach(function (c) {
          var cls  = c.pass ? 'c-log--ok' : 'c-log--err';
          var icon = c.pass ? '&#10003;'  : '&#10005;';
          lines.push(
            '<div class="c-check-row">' +
              '<span class="c-check-icon ' + cls + '">' + icon + '</span>' +
              '<span class="' + cls + '">' + esc(c.label) + '</span>' +
            '</div>'
          );
        });

        if (checks.length > 0 && checks.every(function (c) { return c.pass; })) {
          lines.push('<div class="c-success">All checks passed! Great work.</div>');
        }

        output.innerHTML = lines.join('') || '<span class="c-hint">No output.</span>';
      };
    }

    // Check rules — populated by the Claude API when the exercise loads.
    // Each entry has { label, js_expression } — evaluated via new Function().
    var CHECKS = [];

    // Full exercise context — stored when loadExercise() completes.
    // Used by the review button to provide Claude with the complete picture
    // (task, HTML, checks) so feedback is actually helpful.
    var currentExercise = {};

    function runChecks(doc, code, logs) {
      return CHECKS.map(function (c) {
        var pass = false;
        try {
          var fn = new Function('doc', 'code', 'logs', 'return (' + c.js_expression + ')');
          pass = !!fn(doc, code, logs);
        } catch (e) {
          pass = false;
        }
        return { label: c.label, pass: pass };
      });
    }

    function esc(s) {
      return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    document.getElementById('run-btn').addEventListener('click', run);

    document.getElementById('reset-btn').addEventListener('click', function () {
      jsEditor.setValue('');
      htmlEditor.setValue(currentStarterHtml);
      output.innerHTML = '<span class="c-hint">Run your code to see results.</span>';
      preview.srcdoc = getIframeTemplate();
    });

    // Apply HTML — reloads the iframe with whatever is in the HTML editor.
    // Useful when the learner edits the HTML and wants to see the new structure
    // before running JS against it.
    document.getElementById('apply-html-btn').addEventListener('click', function () {
      preview.srcdoc = getIframeTemplate();
    });

    // Show answer — populate the JS editor with the solution code
    document.getElementById('show-answer-btn').addEventListener('click', function () {
      if (!currentExercise.solution_code) {
        output.innerHTML = '<span class="c-hint">Solution not available for this exercise.</span>';
        return;
      }
      jsEditor.setValue(currentExercise.solution_code);
      output.innerHTML = '<span class="c-hint">Solution loaded. Click <strong>Run</strong> to see it work.</span>';
    });

    document.getElementById('review-btn').addEventListener('click', async function () {
      var code = jsEditor.getValue().trim();
      if (!code) {
        output.innerHTML = '<span class="c-hint">Write some code first, then hit Review!</span>';
        return;
      }
      output.innerHTML = '<span class="c-hint">Getting AI feedback…</span>';
      try {
        // Send the full exercise context to the review API so Claude has the complete picture.
        // This includes the task, HTML, and check rules — not just the code.
        var res  = await fetch('/api/review.php', {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          body:    JSON.stringify({
            code: code,
            topic: <?= json_encode($topic) ?>,
            task_title: currentExercise.task_title,
            task_description: currentExercise.task_description,
            starter_html: currentExercise.starter_html,
            checks: currentExercise.checks,
            mode: 'real'
          }),
        });
        var data     = await res.json();
        var feedback = data.content?.[0]?.text ?? 'Could not get feedback.';
        output.innerHTML =
          '<div style="padding:4px 0;font-family:var(--font-sans);font-size:14px;line-height:1.7;color:var(--color-text)">' +
          esc(feedback).replace(/\n/g, '<br>') + '</div>';
      } catch (e) {
        output.innerHTML = '<span class="c-log c-log--err">Review failed — check your connection.</span>';
      }
    });

    preview.srcdoc = '';

    // ── Load exercise from Claude API on button click ───────────────
    // Calls /api/exercise.php with the topic slug and mode.
    // The API returns JSON with: task_title, task_description, starter_html, checks, next_hint.
    // We use this to populate the task card, HTML editor, and CHECKS array.
    async function loadExercise() {
      if (isLoadingExercise) return;

      var titleEl = document.getElementById('task-title');
      var bodyEl  = document.getElementById('task-body');

      isLoadingExercise = true;
      newChallengeBtn.disabled = true;
      newChallengeBtn.textContent = 'Loading...';
      titleEl.innerHTML = 'Loading exercise… <span class="c-mode-badge <?= h($level_class) ?>"><?= h($level_label) ?></span>';
      bodyEl.innerHTML = '<p class="c-hint">Generating your challenge…</p>';
      CHECKS = [];
      jsEditor.setValue('');
      output.innerHTML = '<span class="c-hint">Run your code to see results.</span>';
      preview.srcdoc = '';

      try {
        var res = await fetch('/api/exercise.php', {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          // Include `level` so the API can tailor the prompt (intermediate =
          // no events, advanced = click handlers + DOM re-rendering).
          body:    JSON.stringify({
            topic: <?= json_encode($slug) ?>,
            mode:  'real',
            level: <?= json_encode($level) ?>
          }),
        });

        if (!res.ok) throw new Error('API returned ' + res.status);

        var exercise = await res.json();

        // If the API returned an error object, show a fallback
        if (exercise.error) throw new Error(exercise.error);

        // Store the full exercise context so the review button can send it to Claude
        // This gives the tutor the complete picture: task, HTML, and checks.
        currentExercise = exercise;

        titleEl.innerHTML = esc(exercise.task_title || '<?= h($topic) ?>') +
          ' <span class="c-mode-badge <?= h($level_class) ?>"><?= h($level_label) ?></span>';

        bodyEl.innerHTML = exercise.task_description || '<p>No description available.</p>';

        // Load the AI-generated HTML template into the editor (if provided)
        if (exercise.starter_html) {
          currentStarterHtml = formatHtmlForEditor(exercise.starter_html);
          htmlEditor.setValue(currentStarterHtml);
          preview.srcdoc = getIframeTemplate();
        }

        // Populate the CHECKS array so runChecks() has real check rules
        if (exercise.checks && exercise.checks.length > 0) {
          CHECKS = exercise.checks;
        }

      } catch (e) {
        // If the API call fails, show a fallback task card
        console.warn('Could not load exercise:', e);

        titleEl.innerHTML = 'Phase ? — <?= h($topic) ?>' +
          ' <span class="c-mode-badge <?= h($level_class) ?>"><?= h($level_label) ?></span>';

        bodyEl.innerHTML =
          '<p>Could not generate exercise — try refreshing the page.</p>' +
          '<ol>' +
          '<li>Read the HTML structure in the editor below</li>' +
          '<li>Write JavaScript that selects and manipulates those elements</li>' +
          '<li>Click <strong>Run</strong> to see your changes live in the preview</li>' +
          '</ol>';
      } finally {
        isLoadingExercise = false;
        newChallengeBtn.disabled = false;
        newChallengeBtn.textContent = 'New Challenge';
      }
    }

    newChallengeBtn.addEventListener('click', loadExercise);
  </script>

</body>
</html>
