<?php
// consolenohtml.php — Study Mode coding challenge (pure JS, no HTML panel).
// The learner writes JavaScript only — no HTML structure to target.
// Output is shown entirely through console.log() in the output panel.
// Exercise content (task card, check rules) is generated by the Claude API
// when the learner clicks "New Challenge".
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/functions.php';
require_login();

$slug  = isset($_GET['topic']) ? $_GET['topic'] : '';
$topic = $slug !== '' ? ucwords(str_replace('-', ' ', $slug)) : 'Unknown Topic';

// Difficulty level — always "beginner" on this page (it is the no-HTML variant),
// but we still read it from the URL and validate it so that:
//   • the value comes from a single source (the URL), not a hard-coded string
//   • an unexpected level from a copy-pasted link falls back safely to beginner
//   • the exercise API can use this exact value in its prompt
$level = isset($_GET['level']) ? $_GET['level'] : 'beginner';
if ($level !== 'beginner') {
    $level = 'beginner';
}

// Minimal iframe template — used as a sandbox to run the learner's JS safely.
// It's hidden from view; the output panel is what the learner reads.
$iframe_template = '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body></body></html>';
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php include __DIR__ . '/includes/favicons.php'; ?>
  <title>Study Mode — <?= h($topic) ?> — SocraticJS</title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/codemirror.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/theme/dracula.min.css">

  <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body class="page--console">

  <!-- ── Navigation ─────────────────────────────────────────────── -->
  <nav class="nav">
    <a href="/index.php"><img class="nav__logo" src="/assets/img/logo.png" alt="SocraticJS logo"></a>
    <a class="nav__link" href="/about.php">about</a>
    <div class="nav__right">
      <?php if (is_logged_in()): ?>
        <span class="nav__greeting">Hi, <?= h($_SESSION["username"]) ?></span>
        <a class="nav__link nav__link--logout" href="/logout.php">logout</a>
      <?php else: ?>
        <a class="nav__link" href="/login.php">login</a>
        <a class="nav__link" href="/register.php">signUp</a>
      <?php endif; ?>
    </div>
  </nav>

  <!-- ── Study Mode widget — JS editor + output only ─────────────── -->
  <div class="console__layout">

    <div class="c-challenge-actions">
      <button class="c-btn c-btn--challenge" id="new-challenge-btn" type="button">New Challenge</button>
    </div>

    <!-- Task card — populated after clicking New Challenge -->
    <div class="c-task-card">
      <div class="c-task-title" id="task-title">
        Ready for a new challenge?
        <span class="c-mode-badge c-mode-beginner">🌱 Beginner</span>
      </div>
      <div class="c-task-body" id="task-body">
        <p class="c-hint">Click <strong>New Challenge</strong> to generate a study-mode exercise for <?= h($topic) ?>.</p>
      </div>
    </div>

    <!-- Toolbar -->
    <div class="c-toolbar">
      <span class="c-toolbar__hint">Write your JS below — hit Run or Ctrl+Enter</span>
      <div class="c-spacer"></div>
      <button class="c-btn c-btn--reset" id="reset-btn">Reset</button>
      <button class="c-btn c-btn--run"   id="run-btn">Run ▶</button>
    </div>

    <!-- JS panel — taller than normal since there is no HTML panel above it -->
    <div class="c-panel" id="js-panel" style="--js-min-height: 480px">
      <div class="c-panel-header">
        <span class="c-dot c-dot--js"></span>
        study.js — write here
      </div>
      <textarea id="js-editor"></textarea>
      <div class="c-js-toolbar">
        <span class="c-toolbar__hint">Done writing?</span>
        <div class="c-spacer"></div>
        <button class="c-btn c-btn--secondary" id="show-answer-btn">Show answer</button>
        <button class="c-btn c-btn--review" id="review-btn">Review my code ↗</button>
      </div>
    </div>

    <!-- Hidden iframe — sandboxes JS execution; not shown to the learner -->
    <iframe id="preview" title="JS sandbox" style="display:none"></iframe>

    <!-- Output panel — the main feedback area in Study mode -->
    <div class="c-panel">
      <div class="c-panel-header">
        <span class="c-dot c-dot--out"></span>
        Output &amp; checks
      </div>
      <div class="c-output" id="output">
        <span class="c-hint">Run your code to see results.</span>
      </div>
    </div>

  </div><!-- /.console__layout -->

  <script src="/assets/js/main.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/codemirror.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/mode/javascript/javascript.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/addon/edit/closebrackets.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/addon/edit/matchbrackets.min.js"></script>

  <script>
    var jsEditor = CodeMirror.fromTextArea(
      document.getElementById('js-editor'),
      {
        mode:              'javascript',
        theme:             'dracula',
        lineNumbers:       true,
        autoCloseBrackets: true,
        matchBrackets:     true,
        indentUnit:        2,
        tabSize:           2,
        indentWithTabs:    false,
        extraKeys: {
          'Ctrl-Enter': run,
          'Cmd-Enter':  run,
          Tab: function (cm) { cm.replaceSelection('  '); }
        }
      }
    );

    // Make the JS editor taller since it is the only editor on the page
    jsEditor.setSize(null, 480);

    var output  = document.getElementById('output');
    var preview = document.getElementById('preview');
    var newChallengeBtn = document.getElementById('new-challenge-btn');
    var HTML_TEMPLATE = <?= json_encode($iframe_template) ?>;
    var isLoadingExercise = false;

    function run() {
      var userJS = jsEditor.getValue().trim();
      if (!userJS) {
        output.innerHTML = '<span class="c-hint">Write some JavaScript first, then hit Run.</span>';
        return;
      }

      output.innerHTML = '<span class="c-hint">Running…</span>';

      // Still use srcdoc + onload for safe sandboxed execution —
      // even though the iframe is hidden, the pattern prevents timing bugs.
      preview.srcdoc = HTML_TEMPLATE;

      preview.onload = function () {
        var win = preview.contentWindow;
        var doc = preview.contentDocument;

        var logs = [];
        var originalLog = win.console.log.bind(win.console);
        win.console.log = function () {
          var args = Array.prototype.slice.call(arguments);
          logs.push(args.map(function (v) { return String(v); }).join(' '));
          originalLog.apply(null, args);
        };

        var runError = null;
        try {
          var fn = new win.Function(userJS);
          fn();
        } catch (e) {
          runError = e.message;
        }

        var lines = [];

        if (logs.length > 0) {
          logs.forEach(function (line) {
            lines.push('<div class="c-log c-log--plain">&#9656; ' + esc(line) + '</div>');
          });
        }

        if (runError) {
          lines.push('<div class="c-log c-log--err">&#10005; Error: ' + esc(runError) + '</div>');
        }

        lines.push('<hr class="c-divider">');

        var checks = runChecks(doc, userJS, logs);
        checks.forEach(function (c) {
          var cls  = c.pass ? 'c-log--ok' : 'c-log--err';
          var icon = c.pass ? '&#10003;'  : '&#10005;';
          lines.push(
            '<div class="c-check-row">' +
              '<span class="c-check-icon ' + cls + '">' + icon + '</span>' +
              '<span class="' + cls + '">' + esc(c.label) + '</span>' +
            '</div>'
          );
        });

        if (checks.length > 0 && checks.every(function (c) { return c.pass; })) {
          lines.push('<div class="c-success">All checks passed! Great work.</div>');
        }

        output.innerHTML = lines.join('') || '<span class="c-hint">No output.</span>';
      };
    }

    // Check rules — populated by the Claude API when the exercise loads.
    var CHECKS = [];

    // Full exercise context — stored when loadExercise() completes.
    // Used by the review button to provide Claude with the complete picture.
    var currentExercise = {};

    function runChecks(doc, code, logs) {
      return CHECKS.map(function (c) {
        var pass = false;
        try {
          var fn = new Function('doc', 'code', 'logs', 'return (' + c.js_expression + ')');
          pass = !!fn(doc, code, logs);
        } catch (e) {
          pass = false;
        }
        return { label: c.label, pass: pass };
      });
    }

    function esc(s) {
      return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    document.getElementById('run-btn').addEventListener('click', run);

    document.getElementById('reset-btn').addEventListener('click', function () {
      jsEditor.setValue('');
      output.innerHTML = '<span class="c-hint">Run your code to see results.</span>';
    });

    // Show answer — populate the JS editor with the solution code
    document.getElementById('show-answer-btn').addEventListener('click', function () {
      if (!currentExercise.solution_code) {
        output.innerHTML = '<span class="c-hint">Solution not available for this exercise.</span>';
        return;
      }
      jsEditor.setValue(currentExercise.solution_code);
      output.innerHTML = '<span class="c-hint">Solution loaded. Click <strong>Run</strong> to see it work.</span>';
    });

    document.getElementById('review-btn').addEventListener('click', async function () {
      var code = jsEditor.getValue().trim();
      if (!code) {
        output.innerHTML = '<span class="c-hint">Write some code first, then hit Review!</span>';
        return;
      }
      output.innerHTML = '<span class="c-hint">Getting AI feedback…</span>';
      try {
        // Send the full exercise context so Claude sees the task, checks, and code together.
        var res  = await fetch('/api/review.php', {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          body:    JSON.stringify({
            code: code,
            topic: <?= json_encode($topic) ?>,
            task_title: currentExercise.task_title,
            task_description: currentExercise.task_description,
            checks: currentExercise.checks,
            mode: 'study'
          }),
        });
        var data     = await res.json();
        var feedback = data.content?.[0]?.text ?? 'Could not get feedback.';
        output.innerHTML =
          '<div style="padding:4px 0;font-family:var(--font-sans);font-size:14px;line-height:1.7;color:var(--color-text)">' +
          esc(feedback).replace(/\n/g, '<br>') + '</div>';
      } catch (e) {
        output.innerHTML = '<span class="c-log c-log--err">Review failed — check your connection.</span>';
      }
    });

    // ── Load exercise from Claude API on button click ───────────────
    // Same as consolehtml.php but for study mode — no HTML editor to populate.
    async function loadExercise() {
      if (isLoadingExercise) return;

      var titleEl = document.getElementById('task-title');
      var bodyEl  = document.getElementById('task-body');

      isLoadingExercise = true;
      newChallengeBtn.disabled = true;
      newChallengeBtn.textContent = 'Loading...';
      titleEl.innerHTML = 'Loading exercise… <span class="c-mode-badge c-mode-beginner">🌱 Beginner</span>';
      bodyEl.innerHTML = '<p class="c-hint">Generating your challenge…</p>';
      CHECKS = [];
      jsEditor.setValue('');
      output.innerHTML = '<span class="c-hint">Run your code to see results.</span>';

      try {
        var res = await fetch('/api/exercise.php', {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          // Include `level` so the API can tailor the prompt to the right
          // difficulty band (beginner here — no HTML, pure console.log).
          body:    JSON.stringify({
            topic: <?= json_encode($slug) ?>,
            mode:  'study',
            level: <?= json_encode($level) ?>
          }),
        });

        if (!res.ok) throw new Error('API returned ' + res.status);

        var exercise = await res.json();
        if (exercise.error) throw new Error(exercise.error);

        // Store the full exercise context so the review button can send it to Claude
        currentExercise = exercise;

        titleEl.innerHTML = esc(exercise.task_title || '<?= h($topic) ?>') +
          ' <span class="c-mode-badge c-mode-beginner">🌱 Beginner</span>';

        bodyEl.innerHTML = exercise.task_description || '<p>No description available.</p>';

        // Populate the CHECKS array so runChecks() has real check rules
        if (exercise.checks && exercise.checks.length > 0) {
          CHECKS = exercise.checks;
        }

      } catch (e) {
        console.warn('Could not load exercise:', e);

        titleEl.innerHTML = 'Phase ? — <?= h($topic) ?>' +
          ' <span class="c-mode-badge c-mode-beginner">🌱 Beginner</span>';

        bodyEl.innerHTML =
          '<p>Could not generate exercise — try refreshing the page.</p>' +
          '<ol>' +
          '<li>Write your JavaScript in the editor below</li>' +
          '<li>Use <code>console.log()</code> to print output</li>' +
          '<li>Click <strong>Run</strong> to test — then <strong>Review</strong> for AI feedback</li>' +
          '</ol>';
      } finally {
        isLoadingExercise = false;
        newChallengeBtn.disabled = false;
        newChallengeBtn.textContent = 'New Challenge';
      }
    }

    newChallengeBtn.addEventListener('click', loadExercise);
  </script>

</body>
</html>
